# Generated by Django 6.1.1 on 2026-09-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_turfslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='opening_time',
        ),
    ]
