# Generated by Django 6.1.1 on 2026-09-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_remove_turf_closing_time_remove_turf_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='map_url',
            field=models.URLField(blank=True),
        ),
    ]
