# Generated by Django 6.1.1 on 2026-09-07 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_method_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_platform',
            field=models.CharField(blank=True, choices=[('', 'Not Selected'), ('razorpay', 'Razorpay'), ('upi', 'UPI'), ('offline', 'Offline Payment')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Online Payment'), ('offline', 'Offline Payment')], default='', max_length=20),
        ),
    ]
