# Generated by Django 6.1.1 on 2026-09-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_booking_group_id_booking_payment_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date', '-start_time']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_group_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('offline', 'Offline Payment')], default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('failed', 'Payment Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting for Admin Approval'), ('approved', 'Approved - Payment Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Rejected / Cancelled')], default='pending', max_length=20),
        ),
    ]
